
services:
  # --- 1. LE CERVEAU KAFKA (Zookeeper) ---
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - nvda-network

  # --- 2. LE TUYAU (Kafka Broker) ---
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: Kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # Configuration pour être accessible depuis Spark (interne) ET ton Python (externe)
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - nvda-network

  # --- 3. LE CHEF D'ORCHESTRE SPARK (Master) ---
  spark-master:
    image: docker.io/bitnamilegacy/spark:3.4
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8080:8080" # Interface Web Spark (Dashboard)
      - "7077:7077" # Port pour soumettre les jobs
    networks:
      - nvda-network

  # --- 4. L'OUVRIER SPARK (Worker) ---
  spark-worker:
    image: docker.io/bitnamilegacy/spark:3.4
    container_name: spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G  # On alloue 2GB de RAM au worker
      - SPARK_WORKER_CORES=2    # 2 cœurs CPU
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    networks:
      - nvda-network

# Création d'un réseau privé pour qu'ils se parlent entre eux
networks:
  nvda-network:
    driver: bridge